--liquibase formatted sql

--changeset kevin:201810211827
--comment:Insert registers into EST_ESTOQUE table

INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD, EST_LOCALIZACAO)VALUES(1,10,'Estoque');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD, EST_LOCALIZACAO)VALUES(2,5,'Estoque');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD, EST_LOCALIZACAO)VALUES(3,9,'Estoque');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD, EST_LOCALIZACAO)VALUES(4,4,'Estoque');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD, EST_LOCALIZACAO)VALUES(5,0,'Estoque');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD, EST_LOCALIZACAO)VALUES(6,30,'Estoque');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD, EST_LOCALIZACAO)VALUES(7,1,'Estoque');

--rollback DELETE FROM EST_ESTOQUE;