--liquibase formatted sql

--changeset kevin:201810211827
--comment:Insert registers into EST_ESTOQUE table


INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD,EST_LOCALIZACAO) VALUES(111,10,'A1');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD,EST_LOCALIZACAO) VALUES(112,5,'A2');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD,EST_LOCALIZACAO) VALUES(113,9,'A3');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD,EST_LOCALIZACAO) VALUES(114,4,'B1');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD,EST_LOCALIZACAO) VALUES(115,0,'B2');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD,EST_LOCALIZACAO) VALUES(116,30,'B3');
INSERT INTO EST_ESTOQUE (EST_ID,EST_QTD,EST_LOCALIZACAO) VALUES(117,1,'G3');

--rollback DELETE FROM EST_ESTOQUE;