--liquibase formatted sql

--changeset kevin:201810211827
--comment:Insert registers into FPG_FORMA_PAGAMENTO table

INSERT INTO FPG_FORMA_PAGAMENTO(FPG_FORMA_PAGAMENTO,FPG_DESCONTO_PAGAMENTO) VALUES('DINHEIRO',0.0);
INSERT INTO FPG_FORMA_PAGAMENTO(FPG_FORMA_PAGAMENTO,FPG_DESCONTO_PAGAMENTO) VALUES('CHEQUE',0.0);
INSERT INTO FPG_FORMA_PAGAMENTO(FPG_FORMA_PAGAMENTO,FPG_DESCONTO_PAGAMENTO) VALUES('CARTAO DE DEBITO',0.0);
INSERT INTO FPG_FORMA_PAGAMENTO(FPG_FORMA_PAGAMENTO,FPG_DESCONTO_PAGAMENTO) VALUES('CARTAO DE CREDITO',0.0)
--rollback DELETE FROM FPG_FORMA_PAGAMENTO;