--liquibase formatted sql

--changeset kevin:201810211827
--comment:Insert registers into VEN_VENDA table

INSERT INTO VEN_VENDA (VEN_ID,CLI_ID,FPG_ID) VALUES(1,5,4);
INSERT INTO VEN_VENDA (VEN_ID,CLI_ID,FPG_ID) VALUES(2,2,2);
INSERT INTO VEN_VENDA (VEN_ID,CLI_ID,FPG_ID) VALUES(3,4,1);
INSERT INTO VEN_VENDA (VEN_ID,CLI_ID,FPG_ID) VALUES(4,1,3);
INSERT INTO VEN_VENDA (VEN_ID,CLI_ID,FPG_ID) VALUES(5,3,5);


--rollback DELETE FROM VEN_VENDA;