--liquibase formatted sql

--changeset kevin:201810211827
--comment:Insert registers into FPG_FORMA_PAGAMENTO table

INSERT INTO FPG_FORMA_PAGAMENTO(FPG_ID,FPG_FORMA_PAGAMENTO,FPG_DESCONTO_PAGAMENTO) VALUES(1,'DINHEIRO',42.00);
INSERT INTO FPG_FORMA_PAGAMENTO(FPG_ID,FPG_FORMA_PAGAMENTO,FPG_DESCONTO_PAGAMENTO) VALUES(2,'CHEQUE',39.99);
INSERT INTO FPG_FORMA_PAGAMENTO(FPG_ID,FPG_FORMA_PAGAMENTO,FPG_DESCONTO_PAGAMENTO) VALUES(3,'CARTAO DE DEBITO'29.47);
INSERT INTO FPG_FORMA_PAGAMENTO(FPG_ID,FPG_FORMA_PAGAMENTO,FPG_DESCONTO_PAGAMENTO) VALUES(4,'CARTAO DE CREDITO',43.76);

--rollback DELETE FROM FPG_FORMA_PAGAMENTO;